### ISSUE TITLE
Doesn't add the JSON to the exported EXE

### ISSUE THREAD

**Issue by Goathier** [toffesource/Godot-Game-Engine-PlayerInventory#6]
The JSON is not compiled when exported in EXE. I played with the ressources options but it doesn't change anything. The only way I made it work is by putting the JSON in the "user://" folder. But it's really easy to change by the users.

Am I doing something wrong?

**Comment by toffesource** [comment]
No, you are not doing anything wrong. In fact the JSON files are supposed to be excluded from the final build, otherwise it will be read-only unless you would want that. In my opinion, the best way to approach this is to encrypt your JSON file's contents. Godot has a built-in method in doing such. 

Kindly refer to this link,
https://docs.godotengine.org/en/3.1/tutorials/io/encrypting_save_games.html
